#!/bin/bash
# shellcheck disable=SC2034
if read -r local_ref local_sha remote_ref remote_sha; then
  if [ master == "${remote_ref##*\/}" ]; then
    updpkgsums
    makepkg -c --printsrcinfo >.SRCINFO
    # README.md часто изменяется, поэтому для него отключаем проверку суммы. В списке файлов он последний.
    N=$(grep -n sha256sums PKGBUILD | cut -d: -f1)
    sed -ri "$N,\$s/[a-z0-9]+'\)/SKIP')/" PKGBUILD
    git add PKGBUILD .SRCINFO
    git commit --amend --no-edit
  fi
fi
